version: '3.4'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private
  api:
    image: justonevote/api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - public
      - private
    ports:
      - 9229:9229
    labels:
      - traefik.enable=true
  client-web:
    image: justonevote/client-web
    build:
      context: .
      dockerfile: ./apps/client/web/Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - public
    labels:
      - traefik.enable=true
  myadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - private
      - public
    labels:
      - traefik.enable=true
networks:
  private:
  public:
    name: traefik_webgateway
    external: true
volumes:
  postgres_data:
    driver: local
